/**
 * Coding as activism
 * TODO: Add Description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Email'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Email'));
  } else {
    // Browser globals (root is window)
    if (!root.CodingAsActivism) {
      root.CodingAsActivism = {};
    }
    root.CodingAsActivism.CreateavolunteerrecordRequest = factory(root.CodingAsActivism.ApiClient, root.CodingAsActivism.Email);
  }
}(this, function(ApiClient, Email) {
  'use strict';




  /**
   * The CreateavolunteerrecordRequest model module.
   * @module model/CreateavolunteerrecordRequest
   * @version 1.0
   */

  /**
   * Constructs a new <code>CreateavolunteerrecordRequest</code>.
   * @alias module:model/CreateavolunteerrecordRequest
   * @class
   * @param firstName {String} 
   * @param lastName {String} 
   * @param emails {Array.<module:model/Email>} 
   */
  var exports = function(firstName, lastName, emails) {
    var _this = this;

    _this['firstName'] = firstName;
    _this['lastName'] = lastName;
    _this['emails'] = emails;
  };

  /**
   * Constructs a <code>CreateavolunteerrecordRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateavolunteerrecordRequest} obj Optional instance to populate.
   * @return {module:model/CreateavolunteerrecordRequest} The populated <code>CreateavolunteerrecordRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('firstName')) {
        obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
      }
      if (data.hasOwnProperty('lastName')) {
        obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
      }
      if (data.hasOwnProperty('emails')) {
        obj['emails'] = ApiClient.convertToType(data['emails'], [Email]);
      }
    }
    return obj;
  }

  /**
   * @member {String} firstName
   */
  exports.prototype['firstName'] = undefined;
  /**
   * @member {String} lastName
   */
  exports.prototype['lastName'] = undefined;
  /**
   * @member {Array.<module:model/Email>} emails
   */
  exports.prototype['emails'] = undefined;



  return exports;
}));


