/**
 * Coding as activism
 * TODO: Add Description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CodingAsActivism) {
      root.CodingAsActivism = {};
    }
    root.CodingAsActivism.Response = factory(root.CodingAsActivism.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Response model module.
   * @module model/Response
   * @version 1.0
   */

  /**
   * Constructs a new <code>Response</code>.
   * @alias module:model/Response
   * @class
   * @param type {String} 
   */
  var exports = function(type) {
    var _this = this;



    _this['type'] = type;


  };

  /**
   * Constructs a <code>Response</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Response} obj Optional instance to populate.
   * @return {module:model/Response} The populated <code>Response</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('action')) {
        obj['action'] = ApiClient.convertToType(data['action'], 'String');
      }
      if (data.hasOwnProperty('activistCodeId')) {
        obj['activistCodeId'] = ApiClient.convertToType(data['activistCodeId'], 'Number');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('surveyQuestionId')) {
        obj['surveyQuestionId'] = ApiClient.convertToType(data['surveyQuestionId'], 'Number');
      }
      if (data.hasOwnProperty('surveyResponseId')) {
        obj['surveyResponseId'] = ApiClient.convertToType(data['surveyResponseId'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} action
   */
  exports.prototype['action'] = undefined;
  /**
   * @member {Number} activistCodeId
   */
  exports.prototype['activistCodeId'] = undefined;
  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Number} surveyQuestionId
   */
  exports.prototype['surveyQuestionId'] = undefined;
  /**
   * @member {Number} surveyResponseId
   */
  exports.prototype['surveyResponseId'] = undefined;



  return exports;
}));


