/**
 * Coding as activism
 * TODO: Add Description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CodingAsActivism);
  }
}(this, function(expect, CodingAsActivism) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CodingAsActivism.RSVPtoaneventRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RSVPtoaneventRequest', function() {
    it('should create an instance of RSVPtoaneventRequest', function() {
      // uncomment below and update the code to test RSVPtoaneventRequest
      //var instance = new CodingAsActivism.RSVPtoaneventRequest();
      //expect(instance).to.be.a(CodingAsActivism.RSVPtoaneventRequest);
    });

    it('should have the property person (base name: "person")', function() {
      // uncomment below and update the code to test the property person
      //var instance = new CodingAsActivism.RSVPtoaneventRequest();
      //expect(instance).to.be();
    });

    it('should have the property event (base name: "event")', function() {
      // uncomment below and update the code to test the property event
      //var instance = new CodingAsActivism.RSVPtoaneventRequest();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instance = new CodingAsActivism.RSVPtoaneventRequest();
      //expect(instance).to.be();
    });

    it('should have the property role (base name: "role")', function() {
      // uncomment below and update the code to test the property role
      //var instance = new CodingAsActivism.RSVPtoaneventRequest();
      //expect(instance).to.be();
    });

    it('should have the property shift (base name: "shift")', function() {
      // uncomment below and update the code to test the property shift
      //var instance = new CodingAsActivism.RSVPtoaneventRequest();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new CodingAsActivism.RSVPtoaneventRequest();
      //expect(instance).to.be();
    });

  });

}));
