/**
 * Coding as activism
 * TODO: Add Description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CodingAsActivism);
  }
}(this, function(expect, CodingAsActivism) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CodingAsActivism.MiscApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MiscApi', function() {
    describe('echoesPost', function() {
      it('should call echoesPost successfully', function(done) {
        //uncomment below and update the code to test echoesPost
        //instance.echoesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('events4306Get', function() {
      it('should call events4306Get successfully', function(done) {
        //uncomment below and update the code to test events4306Get
        //instance.events4306Get(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('people100879417CanvassResponsesPost', function() {
      it('should call people100879417CanvassResponsesPost successfully', function(done) {
        //uncomment below and update the code to test people100879417CanvassResponsesPost
        //instance.people100879417CanvassResponsesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('peopleFindOrCreatePost', function() {
      it('should call peopleFindOrCreatePost successfully', function(done) {
        //uncomment below and update the code to test peopleFindOrCreatePost
        //instance.peopleFindOrCreatePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('signupsPost', function() {
      it('should call signupsPost successfully', function(done) {
        //uncomment below and update the code to test signupsPost
        //instance.signupsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
